GameFeeder/GameFeeder

- config/data_config.json
Adds Dota Underlords as a game.
Sources:
- /u/wykrhm on /r/underlords
Fix #65.
> Add Dota Underlords as a game

- config/data_config.json
Fix Steam icon not displaying.
We now use the Twitter avatar of @steam_games.
> Fix Steam icon not displaying

- README.md
- config/game_config.example.json
- package.json
Temporarily remove the dota blog as a provider to decrease duplicate posts.
Closes #100.
**Checklist**:
> Temporarily remove dota blog (#100)

- package.json
- src/provider_dota.ts
Catch html parsing errors sooner and hide them due to their size. This is a temporary fix for the broken http://www.dota2.com/patches/ page 
**Checklist**:
> Add try-catch block around html parsing

- .github/workflows/docker.yml
- package.json
- yarn.lock
This adds a github action that will publish a docker image tagged with the version and update the latest docker image on https://hub.docker.com/r/gamefeeder/gamefeeder/tags.
Also adds peer dependency of discord.js package
**Checklist**:
> Add github action to publish docker image on release

- README.md
Add "start" and "settings" commands to README. Closes #145.
**Checklist**:
> Add missing commands to README

- package.json
- src/bot_discord.ts
- src/bot_telegram.ts
- src/util.spec.ts
- src/util.ts
When messages are cut off due to the maximum notification length, it is indicated by appending `...`.
Closes #91.
**Checklist**:
> Add indicator to cut off messages

- README.md
- package.json
- src/commands.ts
The notification commands now also match whitespace, so that all paragraphs are sent.
Closes #131.
**Checklist**:
> Fix notification commands only sending the first paragraph

- README.md
- config/game_config.example.json
- package.json
Add Factorio as a game. Its provider is the [Steam Feed](https://steamcommunity.com/games/427520/announcements).
This should warrant a release.
Closes #147.
**Checklist**:
> Add Factorio as a game

- package.json
- src/rss.ts
Fixed RSS HTML to MD conversion failing on `undefined` content.
Closes #159.
**Checklist**:
> Fix md to html conversion throwing an error on empty content

- package.json
- src/reddit/reddit.ts
Deleted reddit posts should be filtered out now, by checking if the post content is `[removed]`. However, this is hard to test, because it only accurs when a post gets deleted immidiately after it gets posted.
Closes #84.
**Checklist**:
> Filter out deleted reddit posts

- .github/workflows/tag-flow.yml
- CONTRIBUTING.md
- README.md
- package.json
- src/_main.ts
- src/bots/bot.ts
- src/bots/discord.ts
- src/bots/telegram.ts
- src/commands/command.ts
- src/commands/commands.ts
- src/notifications/notification.ts
- src/permissions.ts
- src/reddit/reddit_user.ts
- src/user.ts
Handles being missing permissions or access:
- Remove channel data when being removed from a channel (except from a Telegram channel group, not handled by their events)
- Check for writing permissions before sending messages, subscribing and changing the prefix
- Clean up dead channels on startup and before using the `stats` command
Also fixes some issues with async commands and their time measurements.
Closes #43.
**Checklist**:
> Handle missing permissions

- config/games/dota.json
- package.json
Change the Dota filter of /u/TheZett from `Update` to `Dota 2 Update` per the provider's request.
**Checklist**:
> Fix Dota /u/TheZett filter

- docs/README.md
- package.json
- src/bots/bot.ts
- src/bots/discord.ts
- src/bots/telegram.ts
- src/channel.ts
- src/commands/command.ts
- src/commands/commands.ts
- src/managers/data_manager.ts
Removes the permission checks when sending messages to Telegram channels. Hopefully this will fix some channels not recieving notifications or the bot hitting the rate limit.
Additionally, this adds channel labeling. Bot owners can use `label <bot name> <channel id> <channel label>` to add a label to a channel. This will be used during logging to simplify debugging.
Closes #206.
**Checklist**:
> 206 Fix telegram notifications

- src/bots/bot.ts
Fix the bot not recognizing when a user is trying to unsubscribe a game that they have not subscribed to in the first place. This occured when a user did not subscribe to the specified game, but has other subscriptions active.
**Checklist**:
> Fix unsubscribe message

- docs/README.md
- package.json
- src/bots/bot.ts
- src/bots/discord.ts
- src/bots/telegram.ts
- src/commands/commands.ts
Modify `stats` command to take a game to display stats for that specific game.
Usage: `stats <game name (optional)>`
Closes #225.
**Checklist**:
> Add extension to stats command to display stats about a specific game

- config/games/underlords.json
- docs/README.md
- package.json
Adds the [Dota Underlords Steam feed](https://steamcommunity.com/app/1046930/allnews/) as a provider to increase the update coverage for Dota Underlords.
**Checklist**:
> Add the Steam community announcements as feed for Dota Underlords

- .eslintrc.json
- package.json
- src/bots/bot.ts
- src/bots/telegram.ts
- src/channel.ts
- src/managers/data_manager.ts
- yarn.lock
- Add messages to a queue before sending them to avoid hitting the
telegram API rate limit
- Retry sending messages for failed attempts up to max retries
- After max retries have been reached, disable the subscriber
- Skip sending automated messages to subscribers
- Re-enable subscriber if he sends any command
**Checklist**:
> Improve telegram sendMessage()

- config/games/artifact.json
- config/games/csgo.json
- config/games/dota.json
- config/games/factorio.json
- config/games/steam.json
- config/games/tf2.json
- config/games/underlords.json
- docs/README.md
- package.json
Changes the image host of the games' icons to Imgur to insure that the icons are accessable at all times. I also edited the images slightly to improve their display as circular icons.
**Checklist**:
> Change game icon host to Imgur

- config/games/artifact.json
- docs/README.md
- package.json
Replaces the Steam app ID of Artifact to `1269260`, the Artifact 2.0 beta.
Closes #248.
**Checklist**:
> #248 Add Artifact 2.0 beta Steam feed

- config/games/satisfactory.json
- docs/README.md
- package.json
Adds Satisfactory as game, using the [Steam feed](https://steamcommunity.com/games/526870/announcements).
Closes #250.
**Checklist**:
> #250 Add Satisfactory as game

- package.json
- src/bots/discord.ts
- src/util/util.ts
- Limit Discord embed titles if they exceed the maximum length
Closes #289.
**Checklist**:
> #289 Limit Discord embed titles if they exceed the maximum length

- src/managers/config_manager.ts
- src/managers/data_manager.ts
- src/steam/steam_app_news.ts
- src/steam/steam_web_api.ts
This will help merge https://github.com/GameFeeder/GameFeeder/pull/285 by fixing the legitimate `no-use-before-define` errors
> Fix use before define cases

- package.json
- src/bots/bot.ts
- src/bots/discord.ts
- src/bots/telegram.ts
- src/channel.ts
- src/commands/commands.ts
- src/notifications/notification.ts
- src/updater.ts
- src/util/constants.ts
- yarn.lock
- Decoupled updater from bots by using a PubSub topic. The updaters publish notifications to it and the bots subscribe and send messages when a new item is published. This means that updaters no longer wait for all messages to be sent out so we may want to reconsider the values of the recently added `cycleInterval`
- Improved `yarn dev` to not start twice after every change
- Replaced custom types for `turndown` with official from `@types/turndown`
**Checklist**:
> Add pubsub between updater and bots (rebased on main)

- .github/workflows/ci-flow.yml
- .github/workflows/tag-flow.yml
- Fix tagging workflow to use the new GitHub environment variables
- Fix CI workflow to also run on pushes to `main` (for the badges)
Closes #402.
**Checklist**:
> Fix tagging and CI workflow

- package.json
- src/processors/steam_processor.ts
- tests/steam_processor.spec.ts
- Adds support for the Steam `img` tag
- Adds support for the Steam `previewyoutube` tag
- Adds more tests for the Steam pre processor
**Checklist**:
> Fix Steam formatting for images and videos

- config/games/minecraft.json
- package.json
Temporarily disable the broken Minecraft RSS feed until we fix it.
**Checklist**:
> Disable broken minecraft rss

- package.json
- src/processors/steam_processor.ts
- tests/steam_processor.spec.ts
This PR doesn't replace the (terrible) regex logic for parsing with a proper parser, but improves the formatting of Steam posts significantly:
- Retain line and paragraph breaks
- Improve parsing of some tags if they include line breaks
- Improve parsing of list tags
**Screenshots**:
Before:
After:
**Checklist**:
> Improve parsing of Steam markup

- .vscode/settings.json
- Dockerfile
- package-lock.json
- package.json
When running `npm run dev`, everything worked fine.
But with `npm run build && npm run start`, we got the following error:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/dist/src/logger' imported from /app/dist/src/_main.js
at finalizeResolution (node:internal/modules/esm/resolve:264:11)
at moduleResolve (node:internal/modules/esm/resolve:917:10)
at defaultResolve (node:internal/modules/esm/resolve:1130:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36) {
code: …
```
> Fix module resolution
