GameFeeder/GameFeeder

README.md, src/bot.ts, src/bot_discord.ts, src/bot_telegram.ts, src/bot_user.ts, src/command.ts, src/game.ts
* Add user permission checking
* Add possibility to sub / unsub to all games at the same time
=> Add user permissions

config/bot_config.example.json, src/bot.ts, src/bot_discord.ts, src/bot_telegram.ts, src/bot_user.ts, src/command.ts, src/commands.ts, src/util.ts
* Add owner commands as specified in #23 
* Add notifyAll command
* Add notifyGameSubs command
* Add required permissions to the README
=> Owner commands

README.md, src/bot.ts, src/bot_discord.ts, src/bot_telegram.ts, src/channel.ts, src/commands.ts, src/game.ts
* Add stats command
* Update README with user permissions
Closes #18.
=> Add stats command

config/data_config.json, src/game.ts, src/provider_reddit.ts, src/reddit.ts, src/reddit_user.ts
* Add title filters to reddit providers
Closes #27.
=> Add title filters

src/command.ts, src/commands.ts
* Add start command
Closes #20.
=> Start command

.vscode/settings.json, src/bot.ts, src/bot_discord.ts, src/channel.ts, src/commands.ts, src/data.ts, src/game.ts, tslint.json
* Add settings command
Closes #21.
=> Add settings command

README.md
- Remove headline and index from the TOC
=> Improve README.md table of contents

.travis.yml, ecosystem.config.js, package.json, src/bot_logger.ts, src/bot_telegram.ts, src/commands.ts, src/reddit.ts, src/updater.ts, yarn.lock
This will also address https://github.com/TimJentzsch/valveGamesAnnouncerBot/issues/37 by adding several try-catch blocks.
After investigating, the main issue seems to be with the reddit api wrapper. Even when set up using the [Reddit oAuth Helper](https://not-an-aardvark.github.io/reddit-oauth-helper/?state=q8EtLAfYyPzP1TWswixuwOcWrr4qooQJOJGkLhBmTgc%3D&code=LDSTu2iNTXgQxsaoS2s15B8_UqI) and the initialization completes successfully, authentication/authorization errors are returned from the `getUser().getSubmissions()` line.
=> Improve deployment

src/comparable.ts, src/notification.ts, src/reddit.ts, src/rss.ts, src/rss_item.ts, src/updater.ts, src/util.ts, yarn.lock
- Add and implement comparable interface for sorting and limiting arrays
- Fix reddit updates not being sent
=> Fix reddit updates

.travis.yml, jest.config.js, package.json, src/commands.ts, src/util.spec.ts, tsconfig.json, yarn.lock
duplicate of #48 to trigger travis build
=> Add tests and fix package versions

src/bot_discord.ts, src/bot_telegram.ts
Fixes the image link parsing.
Fix #50.
Preview on Discord:
=> Fix image link parsing

src/bot_telegram.ts, src/notification.ts
Fix undefined authors in Telegram.
Fix #52.
=> Fix undefined authors in Telegram

src/bot_discord.ts, src/bot_telegram.ts
Compress to many line breaks together for better readability.
Fix #57.
=> Compress line breaks

src/bot_telegram.ts
Fix #56 (Markdown formatting  in Telegram links).
=> Fix markdown formatting in Telegram links

.vscode/extensions.json
Modify recommended extensions:
- Remove spell checker
- Add markdown all-in-one
=> Remove spell checker, add markdown all in one

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Add a basic pull request template with a checklist so that we don't forget anything.
=> Add a PR template

package.json, src/updater.ts
=> Restart update loop outside of try (closes #95)

data/updater_data.example.json, package.json, src/_main.ts, src/bot_logger.ts, src/data_manager.ts, src/rss.ts, src/updater.ts
- Ignore unnecessary rss item fields and skip update if mandatory fields
are undefined
- Add some startup logging
- Add healthcheck on updater
**Checklist**:
=> Fix rss feed error

package.json, src/bot_telegram.ts
Fixes commands not working in Telegram channels.
Closes #19.
**Checklist**:
=> Fix commands not working in Telegram channels

config/api_config.example.json, package.json, src/_main.ts, src/config_manager.ts, src/package_manager.ts, src/project_manager.ts, src/reddit.ts
Automatically compose reddit user agent with up-to-date project version.
Closes #103.
**Checklist**:
=>  Automatically compose reddit user agent 

README.md, config/game_config.example.json, package.json, yarn.lock
Add /u/Kappa_Man and /u/wickedplayer494 as Dota providers.
Closes #109.
**Checklist**:
=> 109 add dota providers

config/game_config.example.json, package.json, src/config_manager.ts, src/game.ts, src/reddit_user.ts
Fix typo in filter config and initialization in reddit_user object. Also added a few more debug logs.
Closes #108
**Checklist**:
=> Fix reddit titles not being filtered appropriately

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, CONTRIBUTING.md, Dockerfile, docker-compose.yml
- Dockerfile for devcontainer supported by vscode
- Dockerfile and docker-compose for deployment
**Checklist**:
=> Add dockerfiles

CONTRIBUTING.md, README.md, package.json
- Improve the icon formatting for better readability
- Extend the bot description
**Checklist**:
=> Improve README formatting

CONTRIBUTING.md, README.md
Update the documents to accommodate possible contributors from Hacktoberfest
=> Update README and CONTRIBUTING with docker info

.editorconfig, CONTRIBUTING.md, README.md, package.json, yarn.lock
* Cleans up some obsolete EditorConfig rules
* Changes the version constraint for the package introduced in #136, in order to align with the project convention
* Fixes a couple of typos
**Checklist**:
=> Housekeeping: editorconfig, typos, version constraints

package.json, src/_main.ts, src/bot.ts, src/bot_discord.ts, src/bot_logger.ts, src/bot_telegram.ts, src/bot_user.ts, src/command.ts, src/commands.ts, src/init_manager.ts, src/provider_dota.ts, src/reddit.ts, src/reddit_user.ts, src/rss.ts, src/updater.ts
Refactor the logging to use a Logger class that takes the label as parameter.
**Checklist**:
=> 113 improve botlogger

README.md
- Add usage instructions and invite links
- Add preview screenshots
**Checklist**:
=> Add usage instructions and invite links to README

README.md
The Discord invite link now includes requests for the needed permissions (send messages, embed links).
**Checklist**:
=> Update discord link with the needed permissions

src/updater.ts
Improving the updater performance by performing the provider and game updates concurrently. I measured a performance increase from ~10s to ~4s per update cycle.
**Checklist**:
=> Improve updater performance

package.json
Fixing the project version from last update.
=> Update project version to 0.7.6

README.md, package.json, src/bots/bot.ts, src/bots/discord.ts, src/bots/telegram.ts, src/commands/commands.ts
Readds the `stats` command, displaying some statistics about the bot:
**Checklist**:
=> 175 fix stats command

package.json, src/bots/telegram.ts
Fix `NaN` user count when the bot has been removed from a Telegram channel.
**Checklist**:
=> Stats hotfix

package.json, src/_main.ts
Improves the startup performance by starting the bots and registering the commands asynchronously. I measured an improvement of about 1 sec.
The logging in the main method is also compressed and time mesurements are added.
**Checklist**:
=> Improve startup performance

package.json, src/providers/provider.ts, src/providers/provider_reddit.ts, src/reddit/reddit.ts, src/reddit/reddit_post.ts, src/updater.ts
Improves the performance of reddit updates by querying each user asynchronously. Also includes major refactoring changes to make the structure more comprehensible.
I measured a performance increase from ~4 s to ~2 s on the initial update cycle.
**Checklist**:
=> Improve reddit performance

README.md, package.json, src/bots/discord.ts, src/bots/telegram.ts, src/commands/command.ts, src/commands/commands.ts, src/message.ts
Adds three utility commands:
- `debug` command to display useful debug information
- `ping` command to test the delay of the bot
- `telegramCmd` command that simplifies command registering on Telegram
**Checklist**:
=> Add ping, debug and telegramCmd commands

config/games/artifact.json, config/games/csgo.json, config/games/dota.json, config/games/factorio.json, config/games/steam.json, config/games/tf2.json, config/games/underlords.json, docs/README.md, package.json, src/game.ts, src/managers/config_manager.ts, src/reddit/reddit_post.ts
Allows multiple subreddits per game and adjusts the Dota providers so that we hopefully catch all patches now. New providers:
- /r/DotA2:
- /u/wykrhm
- /u/Kappa_Man ('Update')
- /u/TheZett ('Update')
- /r/DotaPatches:
- /u/Kappa_Man ('Update')
- /u/Magesunite ('Update')
- /u/MSTRMN_ ('Update')
- [Blog](http://blog.dota2.com/feed)
- [Gameplay Patches](http://dota2.com/patches)
**Checklist**:
=> Adjust Dota providers

package.json, src/updater.ts
=> Attempt to fix Telegram errors

package.json, src/bots/bot.ts, src/bots/telegram.ts
Removes channel data when being blocked by a Telegram user.
Also changes the logging when properly detecting being removed from a channel from debug to info.
Closes #201.
**Checklist**:
=> 201 telegram user block

package.json, src/bots/telegram.ts, src/channel.ts
Do not remove channel data on Telegram errors until we fixed the error handling.
**Checklist**:
=> No removal on error

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/command-request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/game-request.md
**Description:**
Adds issue templates to request new games and commands.
=> Add issue templates for game and command requests

docs/README.md, package.json
Updates the README and upgrades the package version to `0.11.0`.
Fix for #193 and b68aa599bde185d22ebf3d0bd77945a5629421da.
**Checklist**:
=> Fix package version and readme for #193

Dockerfile, docker-compose.prod.yml, package.json
=> Add games in production image

package.json, src/channel.ts, src/commands/commands.ts
=> Fix label command when providing wrong bot

docs/README.md
Adds a release badge to the README: ![Release](https://img.shields.io/github/v/release/GameFeeder/GameFeeder)
**Checklist**:
=> Add README release badge

package.json, src/reddit/reddit.ts
Limit the reddit error messages to 5000 characters to prevent them from spamming the log.
**Checklist**:
=> Limit reddit error messages to 5000 characters

package.json, src/channel.ts
Fixes a bug where users with no subscriptions could not send any command
**Checklist**:
=> Fix bug with unsubscribed users

package.json, src/_main.ts, src/commands/commands.ts
Fixed a bug where missing data files were not being created on startup.
**Checklist**:
=> Fix files not being created

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .vscode/settings.json
* `autocrlf "true"` was a problem when discarding changes via vscode git, `input` seems to fix that
* added a neat resource monitor plugin
* added some excluded files in vscode workspace settings
=> Further improve devcontainer

.eslintrc.json, package.json, src/bots/bot.ts, src/bots/discord.ts, src/bots/telegram.ts, src/channel.ts, src/commands/command.ts, src/commands/command_group.ts, src/game.ts, src/logger.ts, src/message.ts, src/notifications/notification.ts, src/notifications/notification_builder.ts, src/notifications/notification_element.ts, src/permissions.ts, src/providers/provider.ts, src/providers/reddit_provider.ts, src/providers/rss_provider.ts, src/providers/steam_provider.ts, src/providers/subreddit_provider.ts, src/reddit/reddit_post.ts, src/reddit/reddit_user.ts, src/rss/rss_item.ts, src/telegram_iv_template.ts, src/updater.ts, src/user.ts
Use shorthand for constructor properties
**Checklist**:
=> Use shorthand for constructor properties

src/providers/reddit_provider.ts, src/steam/steam_web_api.ts
Add some missing commits from https://github.com/GameFeeder/GameFeeder/pull/252
=> Add missing commits

codecov.yml
Add codecov.yml to disable annoying PR comments
**Checklist**:
=> Add codecov.yml to disable annoying PR comments

package.json
Upgrades package version to `0.15.0` since I forgot in #317.
**Checklist**:
=> Upgrade package version to 0.15.0 (fixes #317)

codecov.yml
=> Second attempt at hiding codecov annotations

config/games/amongus.json, config/games/deadbydaylight.json, config/games/flightsim.json, config/games/forager.json, config/games/hades.json, config/games/minecraft.json, config/games/rainbow6.json, docs/README.md, package.json
Adds a bunch of more games:
- Among Us (closes #329)
- Dead by Daylight (closes #311)
- Forager (closes #349)
- Hades (closes #350)
- Microsoft Flight Simulator 2020 (closes #310)
- Minecraft (closes #304)
- Rainbow Six Siege (closes #308)
**Checklist**:
=> Add 7 more games

.github/workflows/ci-flow.yml, package.json, src/commands/command.ts, src/commands/command_group.ts, src/commands/commands.ts, src/game.ts, src/providers/dota_provider.ts, src/reddit/reddit.ts, src/reddit/reddit_post.ts
Removed circular dependencies because one of them blocked the tests from running at #342 
**Checklist**:
=> Remove all circular dependencies

.gitignore, .vscode/settings.json, config/schemas/api_config.schema.json, config/schemas/game_config.schema.json
Adds JSON schemas for the game-, api-, and updater-config files.
They are currently only applied in VSCode, later the files should be validated before running the bot.
**Checklist**:
=> Add JSON schemas for the config files

.github/workflows/coverage-flow.yml, .github/workflows/tag-flow.yml, docs/README.md
Changes the workflow branches from `master` to `main`
**Checklist**:
=> Change workflow branches from master to main

package.json, src/bots/bot.ts, src/providers/provider.ts, yarn.lock
Update Typescript to 4.1 and node-html-parser to 2.0
**Checklist**:
=> Update Typescript to 4.1

config/games/cp2077.json, config/games/dota.json, config/games/fallguys.json, docs/README.md, package.json
- Adds Fall Guys: Ultimate Knockout (closes #361)
- Adds Cyberpunk 2077 (closes #401)
- Adds the Steam Community Announcements to Dota providers
- Updates project version to 0.17.2
**Checklist**:
=> Add more games (Fall Guys, Cyberpunk)

package.json, src/commands/commands.ts
- Fixes the game list sorting for `!games`
- Updates project version to 0.17.3
Closes #410.
**Checklist**:
=> Fix game list sorting

package.json, src/providers/dota_provider.ts
A short but meaningful description of the changes you have done.
**Checklist**:
=> Fix error when patches page is changed

config/games/apexlegends.json, config/games/rust.json, config/games/seaofthieves.json, config/games/teamfightmanager.json, config/games/valheim.json, docs/README.md, package.json, src/commands/command.ts
- Fix game recognition being case-sensitive (Closes #443)
- Add more games:
- Apex Legends (Closes #447)
- Rust (Closes #448)
- Sea of Thieves (Closes #445)
- Teamfight Manager (Closes #444)
- Valheim (Closes #446)
**Checklist**:
=> Fix game recognition, add more games

.vscode/extensions.json, Dockerfile
A short but meaningful description of the changes you have done.
**Checklist**:
=> Switch dockerfile to lts node

config/games/ageofempires4.json, docs/README.md, package.json
Adds Age of Empires IV, closes #492.
**Checklist**:
=> Add Age of Empires 4

config/games/gta5.json, docs/README.md, package.json
Add Grand Theft Auto V as game, as it is in the top of Steam games at the moment. Closes #493.
**Checklist**:
=> Add Grand Theft Auto V

docker-compose.prod.yml
Change the docker image repositor and fix volume flags https://github.com/GameFeeder/GameFeeder/issues/388
**Checklist**:
=> Migrate docker compose to new github images

.github/workflows/ci-flow.yml, .github/workflows/coverage-flow.yml, .github/workflows/release-flow.yml, .github/workflows/tag-flow.yml, .vscode/extensions.json, Dockerfile, docs/SETUP.md, package-lock.json, package.json, yarn.lock
Bump nodejs to v18.12.1
**Checklist**:
=> Bump nodejs to v18.12.1

package-lock.json, package.json, src/bots/telegram.ts, src/channel.ts
This PR updates Telegraf to the latest version and fixes errors that resulted from this upgrade.
The permission management is quite annoying now, but oh well.
**Checklist**:
=> Update telegraf 4.11.2

package-lock.json, package.json
telegraf to 4.12.2
turndown to 7.1.2
winston to 3.8.2
**Checklist**:
=> Update minor versions for dependencies

package.json, src/_main.ts, src/bots/telegram.ts
Apparently at some point `telegraf.launch()` was changed into a polling that blocks and therefore blocked any steps after telegram initialization aka the updaters
**Checklist**:
=> Fix telegram never unblocking main

package-lock.json, package.json, src/providers/dota_provider.ts
Overhaul dota provider to use direct endpoint responses instead of scraping the webpage
Closes #312
Closes #556
**Checklist**:
=> Overhaul Dota2 provider

package.json, src/bots/telegram.ts, src/channel.ts
Restore disabling unreachable telegram clients on certain conditions.
**Checklist**:
=> Re-enable unreachable channel disabling

README.md, config/games/davethediver.json, config/games/helldivers2.json, config/games/horizonforbiddenwest.json, config/games/palworld.json, config/games/thronefall.json, package.json
Add the following games:
- Dave the Diver
- Helldivers 2
- Horizon Forbidden West
- Palworld
- Thronefall
**Checklist**:
=> Add 5 new games

Dockerfile, package.json
A short but meaningful description of the changes you have done.
**Checklist**:
=> Fix using non-existent node image tag

.github/workflows/release-flow.yml, .github/workflows/tag-flow.yml
- Fix release flow type
- Refactor tag flow to properly report failures
**Checklist**:
=> Fix github actions

.github/workflows/ci-flow.yml, .github/workflows/release-flow.yml, .github/workflows/tag-flow.yml
- Add missing permissions block
- Re-add tagging step to refactored tag-flow
**Checklist**:
=> Improve github actions
